name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t cicd-app .

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo docker stop cicd-app || true
          sudo docker rm cicd-app || true
          sudo docker pull ubuntu
          sudo docker build -t cicd-app .
          sudo docker run -d -p 80:5000 --name cicd-app cicd-app
